### ISSUE TITLE
红米Rm2100小需求

### ISSUE THREAD

**Issue by izyq** [IvanSolis1989/OpenWrt-DIY#1]
想要三个功能 
接口添加pptp协议支持 
加入插件cifs-mount 
最好用之前的开源驱动  因为现在的闭源驱动无线中继有bug
 
红米没有usb的遗憾是否可以用远程挂载的方式实现？ 

我只知道一个插件luci-app-cifs-mount 
 
但是内核原因也安装不上 
 
所以想请大佬帮忙编译 如果可以的话 谢谢啦

**Comment by IvanSolis1989** [comment]
配置已调整，编译中。到时候下载看看是否否可以了
