### ISSUE TITLE
ShadowsocksR Plus+ 未运行

### ISSUE THREAD

**Issue by Mmilc** [IvanSolis1989/OpenWrt-DIY#11]
ShadowsocksR Plus+ 未运行，刷其他固件也是“ShadowsocksR Plus+ 未运行” 请问这是插件问题还是使用方法没对呢？   路由K2P A1

**Comment by IvanSolis1989** [comment]
这个 我需要百度下

**Comment by yisaya** [comment]
很多K2P的固件酸酸乳没有集成v2ray等，估计你的节点不是ss或者ssr的，所以开不了

**Comment by IvanSolis1989** [comment]
已调整config 再看看吧
