### ISSUE TITLE
x86压缩包文件太大

### ISSUE THREAD

**Issue by kuaner** [IvanSolis1989/OpenWrt-DIY#12]
比方说X86 64的 压缩包有4.3g
实在是太大了，真正解压后用到的其实也就100m的一个镜像

**Comment by IvanSolis1989** [comment]
是的github action默认是吧所有编译结果文件包打包成一个压缩包，下面的网盘链接里面可以下载单个文件。但是网盘有时效性。建议每周五 周六去网盘下载还没过期的编译好的新版。
