### ISSUE TITLE
能否添加自动签到luci-app-jd-dailybonus插件

### ISSUE THREAD

**Issue by eightsheep67** [IvanSolis1989/OpenWrt-DIY#13]
能否添加自动签到luci-app-jd-dailybonus插件

**Comment by IvanSolis1989** [comment]
哪个设备？

**Comment by eightsheep67** [comment]
> 哪个设备？

X86 64，谢谢

**Comment by IvanSolis1989** [comment]
X86 64有这个插件啊？

**Comment by eightsheep67** [comment]
> X86 64有这个插件啊？

https://github.com/jerrykuku/luci-app-jd-dailybonus，我是在trb的固件里发现的
