### ISSUE TITLE
都没法下载啊

### ISSUE THREAD

**Issue by 6907699** [IvanSolis1989/OpenWrt-DIY#14]
我是小白一个，看着干着急，都没法下载

**Comment by IvanSolis1989** [comment]
请阅读 注意事项 里面的下载须知

**Comment by 6907699** [comment]
x86的在哪里下啊，连接都是失效的，大佬给个最新的固件地址啊，谢谢啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IvanSolis1989/OpenWrt-DIY"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 凌晨1:12
收件人:&nbsp;"IvanSolis1989/OpenWrt-DIY"<OpenWrt-DIY@noreply.github.com&gt;;
抄送:&nbsp;"回梦游仙"<6907699@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [IvanSolis1989/OpenWrt-DIY] 都没法下载啊 (#14)





 
Closed #14.
