### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by cheungnut** [IvanSolis1989/OpenWrt-DIY#19]
编译出来不带severchan的，加应用过滤oaf也不会编译出来，diy sh2好像不起效果，主题argon也不会变为新主题，我是r3g

**Comment by cheungnut** [comment]
还有最近刚编译的固件用了后，经常会断线重启，以为是路由器问题，刷回稳定版，又不会了，是新版不稳定吗

**Comment by IvanSolis1989** [comment]
悲剧 怎么回事呢 我的树莓派4编译出来是正常的 我再研究下
