### ISSUE TITLE
生成的固件大于设备容量

### ISSUE THREAD

**Issue by phpszhdyy** [IvanSolis1989/OpenWrt-DIY#22]
建议关闭这个INCLUDE_Kcptun选项

**Comment by IvanSolis1989** [comment]
什么设备

**Comment by phpszhdyy** [comment]
> 什么设备

k2p a1 和小米mini 固件大小都大于16MB了

**Comment by IvanSolis1989** [comment]
按你的要求调整了config

**Comment by phpszhdyy** [comment]
好像除了ssr 那里，还有个地方要关闭，找到个参考链接，还有可能其他的app 太多导致
https://github.com/KevinMX/openwrt-phicomm-k2p-build/issues/5#issuecomment-567841160
https://github.com/coolsnowwolf/lede/issues/2381
https://github.com/coolsnowwolf/lede/issues/1797
找到几个参考链接
