### ISSUE TITLE
能否为树莓派4B添加koolproxyR plus去广告插件呢？

### ISSUE THREAD

**Issue by immyonlystar** [IvanSolis1989/OpenWrt-DIY#27]
你好。请问能否为树莓派4B固件添加koolproxyR plus去广告插件呢，这是我实测目前去电视视频广告效果最好的插件。用的人也很多，可否作为基础插件添加。还有网易云音乐解析插件。谢谢。

**Comment by IvanSolis1989** [comment]
好的 空了解决

**Comment by IvanSolis1989** [comment]
koolproxyR plus是否有持续更新的openwrt源码？
