### ISSUE TITLE
 能否为GL-INET 6416 和 极路由2 hc5761 添加一下

### ISSUE THREAD

**Issue by gpzy1988** [IvanSolis1989/OpenWrt-DIY#29]
能否为GL-INET 6416 极路由2 hc5761 添加一下让便携路由器和老路由焕发一下青春 我之前测试了这俩路由器可以XX上网，这样大家就可以走哪里浪哪里了   便携路由器 GL-INET 6416配置文件我倒是有配好的 不知道怎么附上来

**Comment by IvanSolis1989** [comment]
配置太低 编译了也带不动 没意义
