### ISSUE TITLE
希望添加京东签到助手与luci下的交换机配置

### ISSUE THREAD

**Issue by kuaner** [IvanSolis1989/OpenWrt-DIY#3]
京东签到助手 https://github.com/jerrykuku/luci-app-jd-dailybonus

PS：刷了R3P，发现缺少交换机这个app，想在luci下就可以配置交换机

**Comment by IvanSolis1989** [comment]
交换机插件是什么名字呢？JD签到已经加入

**Comment by kuaner** [comment]
![image](https://user-images.githubusercontent.com/1484437/93187866-d9c32a00-f772-11ea-8836-26e51af78830.png)

就是这个，交换机，但是具体是哪个，我还真不知道，这个应该是自带的，不是第三方插件

**Comment by IvanSolis1989** [comment]
查阅相关资料了解到 如果路由器几个lan口是一个网卡VLAN出来的 就会有交换机选项 如果是一个口对应一个网卡就没有这个选项的
