### ISSUE TITLE
求 网件 7500V2 支持 NTFS 硬盘 

### ISSUE THREAD

**Issue by jerryrat** [IvanSolis1989/OpenWrt-DIY#33]

**Comment by IvanSolis1989** [comment]
插件应该是支持的 不过Openwrt属于定制Linux系统，天生对NTFS支持不好，而且路由器CPU性能偏弱，读写NTFS格式的硬盘不但速度慢而且占用CPU很高，Openwrt挂硬盘建议格式化成EXT4格式使用。
