### ISSUE TITLE
X86版本的WeTransfer显示失效（Transfer expired）

### ISSUE THREAD

**Issue by romejiang** [IvanSolis1989/OpenWrt-DIY#34]
X86版本的WeTransfer一直显示失效。
即便是刚刚编译出来的版本。

![image](https://user-images.githubusercontent.com/1053325/98614089-afd15280-2332-11eb-8748-a482cd4bd15d.png)

**Comment by IvanSolis1989** [comment]
周五编译 只有三天有效期

**Comment by romejiang** [comment]
五小时前编译的X86，64位的在wetransfer还是显示已失效。
我看了一下今天编译的其他固件都在，猜测，可能是因为X86的固件内容比较大（x86 = 4.55G， 其他的都是1.5G左右）导致wetransfer上传失败或者不接受。

![image](https://user-images.githubusercontent.com/1053325/99058864-b84ab700-25d8-11eb-9efc-14a5feb29680.png)
![image](https://user-images.githubusercontent.com/1053325/99059251-49ba2900-25d9-11eb-9554-53ab97b2f34a.png)

**Comment by romejiang** [comment]
这是 transfer 项目的说明，是不是 WeTransfer 超过文件大小限制了
![image](https://user-images.githubusercontent.com/1053325/99061717-edf19f00-25dc-11eb-9388-05124f7facfe.png)
