### ISSUE TITLE
能否加上SmartDNS？

### ISSUE THREAD

**Issue by romejiang** [IvanSolis1989/OpenWrt-DIY#35]
看源码里有smartdns，但安装后菜单里没有。

**Comment by IvanSolis1989** [comment]
哪个设备？

**Comment by romejiang** [comment]
竞斗云，刷的的是上周五11月6号打包的版本

![image](https://user-images.githubusercontent.com/1053325/98781791-e641c700-2431-11eb-92dd-4cedf3b42980.png)

**Comment by IvanSolis1989** [comment]
DNS是不是在“网络”里面？
