### ISSUE TITLE
K3能不能加homeassistant

### ISSUE THREAD

**Issue by fjqzaxljm** [IvanSolis1989/OpenWrt-DIY#40]
老哥K3有空能不添加一个homeassistant。

**Comment by IvanSolis1989** [comment]
具体插件名称  或 源码地址

**Comment by fjqzaxljm** [comment]
> 具体插件名称  或 源码地址
> 

https://github.com/gl-inet/home-assistant-on-openwrt

**Comment by IvanSolis1989** [comment]
A complete installation of Home Assistant will take nearly 350 MB Flash and 130 MB RAM. More components require more storage.
Recommend device is GL-S1300. It has a 8 GB emmc, 512 MB RAM and a Quad-core CPU. It is enough for running Home Assistant and its routing function is also completely unaffected.

**Comment by fjqzaxljm** [comment]
好的，了解，谢谢！

IvanSolis1989 <notifications@github.com> 于 2020年12月28日周一 16:42写道：
