### ISSUE TITLE
nanopi neo2 页面出现两个 Turbo ACC 网络加速

### ISSUE THREAD

**Issue by huangzulin** [IvanSolis1989/OpenWrt-DIY#48]
![QQ截图20201201003758](https://user-images.githubusercontent.com/9855749/100637176-89209d80-336d-11eb-8625-d436fa41bbd3.png)

**Comment by IvanSolis1989** [comment]
已修复

**Comment by qiuqiuuuu** [comment]
k3也有两个

**Comment by qiuqiuuuu** [comment]
> 已修复

k3也有两个
