### ISSUE TITLE
允许opkg update，一直有错误

### ISSUE THREAD

**Issue by wangyz789** [IvanSolis1989/OpenWrt-DIY#55]
错误提示如下，请问要怎解决？
`Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/aarch64_generic/helloworld/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/aarch64_generic/lienol/Packages.gz, wget returned 8.
`

**Comment by IvanSolis1989** [comment]
L大的源码 编译的固件 不能更新openwrt官方源的IPK
