### ISSUE TITLE
建议取消选中ramdisk，不生成initramfs-kernel.bin

### ISSUE THREAD

**Issue by Ljzkirito** [IvanSolis1989/OpenWrt-DIY#57]
建议取消选中ramdisk，不生成initramfs-kernel.bin，以避免某些人刷错文件。
除了开发人员测试，用不到initramfs-kernel.bin文件，也能避免混淆。
将`.config`文件中
`CONFIG_TARGET_ROOTFS_INITRAMFS=y`替换为
`# CONFIG_TARGET_ROOTFS_INITRAMFS is not set`即可
已发pr #58 ，希望合并

**Comment by IvanSolis1989** [comment]
已处理
