### ISSUE TITLE
请求以xray替代v2ray

### ISSUE THREAD

**Issue by PaPerseller** [IvanSolis1989/OpenWrt-DIY#64]
请求以xray替代v2ray以在passwall和ssrplus上获得更完整的功能以及更好的vless性能

**Comment by IvanSolis1989** [comment]
最新编译的固件貌似已经支持XRAY

**Comment by PaPerseller** [comment]
> 最新编译的固件貌似已经支持XRAY

部分固件如r2s已加入，但ac2100等还未更新config文件。若担心占用空间太多，则建议在这种小容量设备上直接以xary替换。
