### ISSUE TITLE
SSH connection Always not allowed.

### ISSUE THREAD

**Issue by latiefkhan** [IvanSolis1989/OpenWrt-DIY#68]
How tof ix.?

**Comment by be-engineer** [comment]
me too。error message is:
Permission denied, please try again.

**Comment by a00789123** [comment]
一样样……的问题，不知道是我不懂玩dropbear还是咋滴。

**Comment by zoraaa** [comment]
我也一样。。。

配了公钥也是不行。。。

**Comment by XiaoSong0919** [comment]
> me too。error message is:
> Permission denied, please try again.

The password is “password”,please try to use it password to login in ssh.

**Comment by azraelrabbit** [comment]
兄弟,我折腾了一天,才找到这个问题... @XiaoSong0919 
第三个办法: 

修改 `config/linksys-extra.config  ` 文件
增加 一行  `CONFIG_PACKAGE_zsh=y`


重新编译生成固件,也能解决.

**Comment by azraelrabbit** [comment]
另外,刚刚看了一下, 
MIPS的所有机型也都会有这个问题,
`config/MIPS/MIPS-extra.config`
文件里也没有默认编译 zsh

**Comment by azraelrabbit** [comment]
> > 另外,刚刚看了一下,
> > MIPS的所有机型也都会有这个问题,
> > `config/MIPS/MIPS-extra.config`
> > 文件里也没有默认编译 zsh
> > 其他的都正常.
> 
> https://github.com/IvanSolis1989/OpenWrt-DIY/pull/85/files
> 这样子修改试试

不额外编译zsh还是会有问题的,因为是在 
`scripts/diy-part3.sh`
里面替换了默认ash 到 zsh
依然还是会有找不到zsh 的问题存在. 
第四种办法:
直接去掉 `scripts/diy-part3.sh` 里面的 

```
# Change default shell to zsh
sed -i 's/\/bin\/ash/\/usr\/bin\/zsh/g' package/base-files/files/etc/passwd
```
这两行,其他什么都不要改动.
再编译固件就没问题了.

**Comment by cxgreat2014** [comment]
八个小时前发现这一问题，三个小时前自行修改zsh到ash解决，感觉这个问题可以reopen一下

**Comment by isecret** [comment]
2021年8月8日，最新版本 newifi d2 的固件问题依然存在。
