### ISSUE TITLE
RedMi AC2100 WIFI 找不到MAC地址过滤。

### ISSUE THREAD

**Issue by igithublab** [IvanSolis1989/OpenWrt-DIY#69]
WIFI的设置项目中找不到MAC地址过滤的设置。另外这个固件发现没有 /etc/config/wireless 的配置文件。

**Comment by XiaoSong0919** [comment]
x86不自带/etc/config/wireless ，并且此固件也不支持wireless

**Comment by igithublab** [comment]
已经弄明白了，这个固件使用的是闭源驱动。谢谢！
