### ISSUE TITLE
K3能增加cups插件吗？

### ISSUE THREAD

**Issue by fjqzaxljm** [IvanSolis1989/OpenWrt-DIY#7]
K3想安装cups，但目前都没看到cups.ipk插件，希望帮编译一个K3使用的CUPS插件。

**Comment by IvanSolis1989** [comment]
你说的是 libcups  这个插件？

**Comment by fjqzaxljm** [comment]
> 你说的是 libcups 这个插件？

应该是吧…用来打印服务的…

**Comment by IvanSolis1989** [comment]
已经加入

**Comment by fjqzaxljm** [comment]
> 已经加入

谢谢！

**Comment by fjqzaxljm** [comment]
> 已经加入

刷了好像没看到cups。哪里出问题？

**Comment by IvanSolis1989** [comment]
肯定是某个依赖没加上。等我有时间了 研究下

**Comment by fjqzaxljm** [comment]
> 肯定是某个依赖没加上。等我有时间了 研究下

谢谢大神的工作，有结果跟大伙分享一下，谢谢！
