### ISSUE TITLE
x86能否加入hyper-v驱动

### ISSUE THREAD

**Issue by PQFitz** [IvanSolis1989/OpenWrt-DIY#75]
hyper-v 第二代 用着用着 就显示网络是拔出状态了 请求添加一下hyper-v的支持 谢谢啦！
最好编译的时候能选上build hyper-v image 这样不用每次都转换了 哈哈

**Comment by IvanSolis1989** [comment]
有这个选项吗？

**Comment by XiaoSong0919** [comment]
> hyper-v 第二代 用着用着 就显示网络是拔出状态了 请求添加一下hyper-v的支持 谢谢啦！
> 最好编译的时候能选上build hyper-v image 这样不用每次都转换了 哈哈

你好，hyper-v以及VMWARE的驱动OP都是默认带上的，不需要再添加的

**Comment by XiaoSong0919** [comment]
> hyper-v 第二代 用着用着 就显示网络是拔出状态了 请求添加一下hyper-v的支持 谢谢啦！
> 最好编译的时候能选上build hyper-v image 这样不用每次都转换了 哈哈

第二个问题，OpenWrt暂不支持输出VHD或VHDX格式的虚拟磁盘文件，只能输出VMDK或VDI格式的虚拟磁盘
