### ISSUE TITLE
R3G添加qBittorrent

### ISSUE THREAD

**Issue by hx210** [IvanSolis1989/OpenWrt-DIY#82]
R3G可以加个qBittorrent我想挂着下资源以及usb3.0支持

**Comment by IvanSolis1989** [comment]
3G只是个MIPS设备 性能真的跑不动这些……

**Comment by hx210** [comment]
那树莓派3b可以加吗qBittorrent

**Comment by IvanSolis1989** [comment]
没有找到一直稳定更新的 qBittorrent 源码

**Comment by hx210** [comment]
好的，谢谢

**Comment by hx210** [comment]
LuCI ---> Applications ---> luci-app-qbittorrent  #BT下载工具（qBittorrent） 这个能用吗

**Comment by XiaoSong0919** [comment]
> LuCI ---> Applications ---> luci-app-qbittorrent #BT下载工具（qBittorrent） 这个能用吗

可以

**Comment by IvanSolis1989** [comment]
可怕 我没注意到

**Comment by IvanSolis1989** [comment]
已经加了 在编译
