### ISSUE TITLE
不知道是不是BUG来的，望各位解答下！

### ISSUE THREAD

**Issue by nanchuci** [IvanSolis1989/OpenWrt-DIY#84]
R3G固件，闭源驱动，操作LAN口里面的各项设置，确认保存后，无线就关闭了，而且重启后依然是关闭状态，只能手动重启无线！

**Comment by XiaoSong0919** [comment]
> R3G固件，闭源驱动，操作LAN口里面的各项设置，确认保存后，无线就关闭了，而且重启后依然是关闭状态，只能手动重启无线！

删除闭源驱动，使用开源驱动即可；目前MT7621闭源驱动仅R3P支持度较好

**Comment by nanchuci** [comment]
> > R3G固件，闭源驱动，操作LAN口里面的各项设置，确认保存后，无线就关闭了，而且重启后依然是关闭状态，只能手动重启无线！
> 
> 删除闭源驱动，使用开源驱动即可；目前MT7621闭源驱动仅R3P支持度较好

目前只找到一个没有这个问题的固件：https://www.right.com.cn/forum/thread-4046998-1-1.html，这位仁兄编译的固件没有此问题，而且有线连接的时候设置无线的时候不会短时断网！

**Comment by XiaoSong0919** [comment]
> https://www.right.com.cn/forum/thread-4046998-1-1.html

我建议最好用开源的，闭源R3G的并不理想，设置较繁琐

**Comment by nanchuci** [comment]
> 我建议最好用开源的，闭源R3G的并不理想，设置较繁琐

哦，谢谢你的建议！其实我反应这个问题，是想看看有没有能修复此问题的方法！
