### ISSUE TITLE
x86的包太大了。

### ISSUE THREAD

**Issue by KevinZjYang** [IvanSolis1989/OpenWrt-DIY#93]
编译的时候只上传最后安装包所在的文件夹就可以了。

**Comment by qiaoyun680** [comment]
> ……我也不想他这么大啊

有个建议,能否上传用的最多的几个固件比如openwrt-x86-64-generic-squashfs-combined-efi.img.gz这种,现在上传的好多固件都不常用,有需要的自己下载bin目录自己解压就好了,建议仅供参考

**Comment by qiaoyun680** [comment]
还有能否把编译过后的package包单独上传一下?感谢

**Comment by IvanSolis1989** [comment]
代码怎么写呢？我去研究下……

**Comment by qiaoyun680** [comment]
> 代码怎么写呢？我去研究下……

我去提一个pr吧 :)
