### ISSUE TITLE
希望添加AppFilter 应用过滤插件

### ISSUE THREAD

**Issue by ssitssit** [IvanSolis1989/OpenWrt-DIY#98]
希望添加AppFilter 应用过滤插件
https://github.com/destan19/OpenAppFilter

**Comment by IvanSolis1989** [comment]
什么设备嘛

**Comment by IvanSolis1989** [comment]
使用说明
应用过滤和加速模块（Turbo ACC)有冲突，需要关闭Turboo ACC后使用

存在的问题
该模块只工作在路由模式， 旁路模式、桥模式不生效
存在小概率误判的情况，特别是同一个公司的app，比如淘宝、支付宝等，如果需要过滤，建议相似的app全部勾选
暂不兼容OpenWrt主干的luci，如果报错，请使用老一点的版本（OpenWrt18.06或lean 的lede源码）

**Comment by ssitssit** [comment]
> 使用说明
> 应用过滤和加速模块（Turbo ACC)有冲突，需要关闭Turboo ACC后使用
> 
> 存在的问题
> 该模块只工作在路由模式， 旁路模式、桥模式不生效
> 存在小概率误判的情况，特别是同一个公司的app，比如淘宝、支付宝等，如果需要过滤，建议相似的app全部勾选
> 暂不兼容OpenWrt主干的luci，如果报错，请使用老一点的版本（OpenWrt18.06或lean 的lede源码）

是的，虽然存在上面的问题，但不影响使用，我的设备是N1、贝壳云都是当主路由使用，希望增加这个插件

**Comment by IvanSolis1989** [comment]
嗯嗯  不过我也是没懂 为何在家还需要应用过滤……
