### ISSUE TITLE
能不能做精简版固件

### ISSUE THREAD

**Issue by Omoinemie** [IvanSolis1989/OpenWrt-DIY#99]
现在的固件太臃肿了，如果采用基础精简版固件+搭建插件服务器自行安装升级的方式更佳。
特点：精简稳定，自装插件自由度高。

**Comment by IvanSolis1989** [comment]
可是我不会这么高级的操作啊 怎么弄？可以教我嘛？

**Comment by IvanSolis1989** [comment]
推荐 苏凌哥哥的 精简固件 https://github.com/SuLingGG/OpenWrt-Mini
